import random

# Write your error handling block here
print(random.randinteger(5,15))
